[build]
phases = { setup = { nixPkgs = ["python312", "postgresql_16.dev", "gcc"] } }

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[phases.release]
cmds = ["python manage.py migrate --no-input"]

[start]
cmd = "gunicorn fusion_force.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"