# Generated by Django 5.2.6 on 2025-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pamela Robinson', max_length=200)),
                ('description', models.TextField(default='Pamela Robinson is a keynote speaker, corporate and leadership trainer, founder of Fusion Force and a recognized expert in sales and marketing support for hospitality companies.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('bullet_points', models.TextField(default='Keynote Speaker\nLeadership Trainer\nHospitality Expert\nGlobal Experience', help_text='Enter each bullet point on a new line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('event_details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Form Submission',
                'verbose_name_plural': 'Contact Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate Leadership'), ('empowerment', 'Women Empowerment'), ('hospitality', 'Hospitality Awards'), ('latest', 'Latest Event'), ('keynote', 'Keynote Speaking'), ('training', 'Corporate Training')], default='corporate', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher number appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fusion Force LLC', max_length=200)),
                ('subtitle', models.TextField(default='Pamela Robinson - Making the Impossible Possible through transformative speaking, corporate training, and leadership development.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Monthly Newsletter', max_length=200)),
                ('subtitle', models.CharField(default='Get exclusive insights and industry updates delivered to your inbox', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Newsletter cover image', null=True, upload_to='newsletter/')),
                ('benefits', models.TextField(default='Leadership Strategies\nIndustry Updates\nCase Studies\nEvent Announcements\nExclusive Content\nSuccess Stories', help_text='Add each benefit on a new line')),
                ('form_title', models.CharField(default='Join Our Community', max_length=200)),
                ('form_description', models.TextField(default='Get exclusive leadership insights, industry trends, and event updates delivered directly to your inbox each month.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Content',
                'verbose_name_plural': 'Newsletter Content',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(choices=[('newsletter_section', 'Newsletter Section'), ('footer', 'Website Footer')], default='newsletter_section', max_length=50)),
                ('agreed_to_terms', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('keynote', 'Keynote Speaking'), ('training', 'Corporate Training'), ('consulting', 'Strategic Consulting')], max_length=50)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-microphone)', max_length=100)),
                ('topics', models.TextField(help_text='Enter topics separated by commas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonial_avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
