# Generated by Django 5.2.6 on 2025-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeContent',
        ),
    ]
