# Generated by Django 5.2.6 on 2025-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_homecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fusion Force LLC', max_length=200)),
                ('subtitle', models.TextField(default='Pamela Robinson - Making the Impossible Possible through transformative speaking, corporate training, and leadership development.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
